mongodb:
  image: mongo
  container_name: mongodb
backend:
  build: .
  container_name: backend
  ports:
    - "3000:3000"
  environment:
    - MONGO_URL=mongodb://mongodb/inventory
  links:
    - mongodb
